steps:
  #Reservations
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/reservations/production',
      '-f',
      'apps/reservations/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/reservations/production'
    ]

  #Auth

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/auth/production',
      '-f',
      'apps/auth/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/auth/production'
    ]

  #Payments

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/payments/production',
      '-f',
      'apps/payments/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/payments/production'
    ]

  #Notifications

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/notifications/production',
      '-f',
      'apps/notifications/Dockerfile',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'southamerica-west1-docker.pkg.dev/sleeper-411323/notifications/production'
    ]