apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-http
spec:
  ports:
  - name: "http"
    port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: auth
    #checa primero service-tcp. Como es internal service, se elige ClusterIp.
    #pero si le ponemos NodePort, lo hacemos un external service.
  type: NodePort
