services:
  e2e:
    build:
      dockerfile: ./dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: southamerica-west1-docker.pkg.dev/sleeper-411323/reservations/production
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: southamerica-west1-docker.pkg.dev/sleeper-411323/auth/production
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: southamerica-west1-docker.pkg.dev/sleeper-411323/payments/production
    env_file:
      - ../apps/payments/.env
  notifications:
    image: southamerica-west1-docker.pkg.dev/sleeper-411323/notifications/production
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo