apiVersion: v1
kind: Service
metadata:
  labels:
    app: reservations
  name: reservations
spec:
  ports:
  - name: 'http'
    port: 3004
    protocol: TCP
    targetPort: 3004
  selector:
    app: reservations
    #because reservations will be hit by http requests, we need it as a nodeport.
  type: NodePort
  #si quisieras acceder directamnete al nodeport, debes agregarle una propiedad más: Nodeport:
  #y elegir el port entre 30000 - 32767
  #el acceso final será <ip address>:<Nodeport value>
